version: 2.1
# main goal:
# deploy-job when run on main, looks up the latest REAL_VERSION file.
# artifacts likely better?

executors:
  basic:
    docker:
      - image: cimg/base:stable
    resource_class: small

parameters:
  version-filepath:
    type: string
    default: "LAST_VERSION.txt"

jobs:
  build-job:
    executor: basic
    steps:
      - checkout
      - run: |
          echo 'export BUILD_NUM=$((CIRCLE_BUILD_NUM + 500000))' >> $BASH_ENV
          echo 'export APP_VERSION=4.18-${BUILD_NUM}' >> $BASH_ENV
      - run: |
          echo "${APP_VERSION}" > << pipeline.parameters.version-filepath >>
      - store_artifacts:
          path: << pipeline.parameters.version-filepath >>

  deploy-job:
    executor: basic
    steps:
      - checkout
      - run: |
          # see what PRs are involved here.
          printenv CIRCLE_PULL_REQUESTS || true

workflows:
  pull-request:
    jobs:
      - build-job:
          filters:
            branches:
              ignore:
                - main
                - /release_.*/
  on-main:
    jobs:
      - deploy-job:
          filters:
            branches:
              only:
                - main
                - /release_.*/
