version: 2.1
# main goal:
# deploy-job when run on master, looks up the latest REAL_VERSION file.
# artifacts likely better?

executors:
  basic:
    docker:
      - image: cimg/base:stable
    resource_class: small

jobs:
  build-job:
    executor: basic
    steps:
      - checkout
      - run: |
          echo 'export BUILD_NUM=$((CIRCLE_BUILD_NUM + 500000))' >> $BASH_ENV
          echo 'export APP_VERSION=4.18-${BUILD_NUM}' >> $BASH_ENV
      - run: |
          printenv APP_VERSION

  # deploy-job:

workflows:
  pull-request:
    jobs:
      - build-job
          # filters:
          #   branches:
          #     ignore:
          #       - main
          #       - /release_.*/
